### Registrar un usuario
POST http://localhost:3001/api/user/signup
Content-Type: application/json

{
  "Nombre": "nombre",
  "Email": "email",
  "Id_Credencial": "credencial",
  "Password": "123"
}

### Inicia sesion con un usuario
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
  "Id_Credencial": "credencial",
  "Password": "123"
}

### Inicia sesion con un usuario
POST http://autenticacion-global-dreamlab.azurewebsites.net/api/user/login
Content-Type: application/json

{
  "Id_Credencial": "credencial",
  "Password": "123"
}

### Obtiene todos los usuarios
GET http://localhost:3001/api/user

### Obtiene un usuario por id
GET http://localhost:3001/api/user/664256e02cbea434fb020316

### Editar un usuario por id
PUT http://localhost:3001/api/user/664256e02cbea434fb020316
Content-Type: application/json

{
  "Nombre": "Nombre modificado",
  "Email": "email modificado",
  "Id_Credencial": "credencial",
  "id": "664256e02cbea434fb020316"
}

### Eliminar un usuario por id
DELETE http://localhost:3001/api/user/6642583bdb097da203e7ba81
